"use client";

import { useState } from "react";
import { Card } from "../ui/FormCard";
import { FormHeader } from "../ui/FormHeader";
import { OtpInput } from "../ui/otp-input";
import { Button } from "../ui/button";
import { maskEmail } from "@/lib/maskEmail";
import { useVerifyTwoFactor } from "@/lib/services/auth.service";

export default function VerifyTwoFactor() {
  const [code, setCode] = useState("");

  const verifyEmail =
    typeof window !== "undefined" ? localStorage.getItem("twoFAEmail") : null;

  const { mutate, isPending, error } = useVerifyTwoFactor();

  const handleVerify = () => {
    const userId = localStorage.getItem("twoFAUserId");

    if (!userId) return;

    const payload = {
      userId,
      code,
    };

    console.log(payload);

    mutate(payload);
  };

  return (
    <Card className="max-sm:justify-center max-sm:text-center">
      <FormHeader
        title="Two-Factor Authentication"
        subtitle={
          <>
            Enter the 6-digit code generated by your authenticator app for{" "}
            {verifyEmail ? maskEmail(verifyEmail) : "your account"}.
          </>
        }
      />

      <OtpInput
        onChange={setCode}
        error={error?.message}
      />

      <Button
        onClick={handleVerify}
        disabled={code.length !== 6 || isPending}
        variant={code.length === 6 && !isPending ? "default" : "disabled"}
        className="w-full"
      >
        {isPending ? "Verifying..." : "Verify Code"}
      </Button>
    </Card>
  );
}
